apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "UjEyMzQ1NmI="
  MYSQL_DATABASE: "cGhvbmVib29r"
  MYSQL_USER : "YWRtaW4="
  MYSQL_PASSWORD: "Q2xhcnVzXzEyMzQ="
  
