apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
  namespace: default
  labels:
    app: result-server
spec:
  selector:
    matchLabels:
      app: result-server
      tier: fronted
  replicas: 1
  template:
    metadata:
      labels:
        app: result-server
        tier: fronted
    spec:
      containers:
      - name: result-server
        image: balaban/result-server
        envFrom:
          - secretRef:
              name: mysqlsecret 
          - configMapRef:
              name: server-config              
        ports:
        - containerPort: 80